// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for linux - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return linux;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-7uSEQoJWk0i9jehtGb9k89RwoxlI5Q',
    appId: '1:116498733500:web:39065d1a401072825c33b9',
    messagingSenderId: '116498733500',
    projectId: 'elhantor-3f993',
    authDomain: 'elhantor-3f993.firebaseapp.com',
    storageBucket: 'elhantor-3f993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCax-4jSKweGzhvxPoUUzPbB5jGgoNulh8',
    appId: '1:116498733500:android:640fc209466038735c33b9',
    messagingSenderId: '116498733500',
    projectId: 'elhantor-3f993',
    storageBucket: 'elhantor-3f993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvDQa6Uwt_Sck1JekUJx7k2qd5HEMzo8',
    appId: '1:116498733500:ios:4d08b83905a2a23f5c33b9',
    messagingSenderId: '116498733500',
    projectId: 'elhantor-3f993',
    storageBucket: 'elhantor-3f993.appspot.com',
    iosClientId:
        '116498733500-ub3sg2m6693tv815nfbg8c3ino2vjki5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvDQa6Uwt_Sck1JekUJx7k2qd5HEMzo8',
    appId: '1:116498733500:ios:4d08b83905a2a23f5c33b9',
    messagingSenderId: '116498733500',
    projectId: 'elhantor-3f993',
    storageBucket: 'elhantor-3f993.appspot.com',
    iosClientId:
        '116498733500-ub3sg2m6693tv815nfbg8c3ino2vjki5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAcvDQa6Uwt_Sck1JekUJx7k2qd5HEMzo8',
    appId: '1:116498733500:ios:4d08b83905a2a23f5c33b9',
    messagingSenderId: '116498733500',
    projectId: 'elhantor-3f993',
    storageBucket: 'elhantor-3f993.appspot.com',
    iosClientId:
        '116498733500-ub3sg2m6693tv815nfbg8c3ino2vjki5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject',
  );
}
